//> using scala "3.3.4"
//> using dep "dev.zio::zio:2.1.24"
//> using dep "dev.zio::zio-http:3.7.4"
//> using dep "dev.zio::zio-json:0.8.0"
//> using dep "dev.zio::zio-schema:1.7.6"
//> using dep "dev.zio::zio-config:4.0.6"
//> using dep "dev.zio::zio-logging:2.5.2"
//> using dep "dev.zio::zio-streams:2.1.24"
//> using dep "dev.zio::zio-test:2.1.24"

//> using testFramework "zio.test.sbt.ZTestFramework"
